spring:
  cloud:
    gateway:
      server:
        webflux:
          defaultFilters:
            - TokenRelay=
          routes:
            - id: test-service
              uri: http://localhost:8040
              predicates:
                - Path=/test/**

csm:
  platform:
    gateway:
      contextPath: "/"
      port: 8060
    identityProvider:
      serverBaseUrl: "http://localhost:8080"
      authorizationGrantType: "authorization_code"
      identity:
        clientId: "idp-gateway-client"
        clientSecret: "changeme"
        tenantId: "changeme"
      scope:
        - "openid"